services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://grahpanchal_db_user:UYnjFLsDA3IV5UUf@mern-todo.n8safub.mongodb.net/?appName=mern-todo
      - JWT_SECRET=mern_todo_super_secret_key_2024
      - JWT_EXPIRE=7d
      - PORT=5000
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge